# Generated by Django 2.1.2 on 2018-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('released', models.DateField(verbose_name='date released')),
                ('duration', models.TimeField()),
                ('price', models.FloatField()),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('CO', 'Comedy'), ('RO', 'Romance'), ('HO', 'Horror'), ('TH', 'Thriller')], default='AC', max_length=20)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
