# Generated by Django 2.1.2 on 2018-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierental', '0002_auto_20181030_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
