# Generated by Django 2.1.2 on 2018-10-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movierental', '0004_auto_20181031_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rentedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movierental.Customer'),
        ),
    ]
