# Generated by Django 2.1.2 on 2018-10-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierental', '0005_movie_rentedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rented',
        ),
    ]
